name: Build

on:
  pull_request:
    types: [ opened, ready_for_review, synchronize ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: corretto
        java-version: 17
    - name: gradlew 실행 권한 추가
      run: chmod +x ./gradlew
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Build
      run: ./gradlew build
    - name: Upload APK files
      id: upload_apk
      uses: actions/upload-artifact@v3
      with:
        name: apk
        path: app/build/outputs/apk/
    - name: PR에 APK artifact URL 코멘트 추가
      uses: actions/github-script@v6
      if: github.event_name == 'pull_request'
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '${{ steps.upload_apk.outputs.artifact_url }}'
          })
